kind: Service                             
apiVersion: v1
metadata:
  name: bikash
  labels:
    app: bikash
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: bikash                    
  type: LoadBalancer  
